### ISSUE TITLE
No output when using 'service service-name status' on a stopped service

### ISSUE THREAD

**Issue by kandarp1691** [mwilliamson/spur.py#45]
```
`try:
        shell = spur.SshShell(hostname=server_address,
                              username='abc',
                              password='xyz', missing_host_key=spur.ssh.MissingHostKey.accept, connect_timeout=100)

        with shell:
            result = shell.run(['service', service_name, 'status'])
            print result.output`

```
So this works perfect is a service is running. But if a service is stopped, does return/print anything.
1. Tried using result.stderr_output but still no output.
2. Works perfectly over plain ssh
3. Works good if the same service is running and command is called.
4. Does return output when using pxssh

**Comment by mwilliamson** [comment]
What happens if you try using `shell_type=spur.ssh.ShellTypes.minimal` in the call to `SshShell()`?

**Comment by kandarp1691** [comment]
I used `shell_type=spur.ssh.ShellTypes.minimal`  and added the following line in my code:
`except spur.RunProcessError as e:
        print e.stderr_output`
On debugging, it shows 
`e: return code: 3\noutput: b'apache-tomcat is stopped\n'\nstderr output: b''`

However, I am not sure how to get it as an output in the terminal.

**Comment by mwilliamson** [comment]
Ah, it's raising an exception because of the return code -- was another part of your code swallowing the exception?

In any case, if you want to always return a result (rather than raising) regardless of the return code, use `allow_error=True` in the call to `run()`.

**Comment by kandarp1691** [comment]
Runs perfectly now. Thanks Mike !

P.S. What do you mean by swallowing an exception. I'm 2 months old to this and would definitely like to learn more about it. Can you point me to a link/page I could refer to get in depth and avoid such mistakes ?

Thanks again !

**Comment by mwilliamson** [comment]
Glad you got it working.

The code you originally was raising an exception. Normally, unless you have an `except` block, Python should exit with the exception printed out. For instance:

```
$ python -c 'raise Exception()'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Exception
```

I was curious whether you saw such a problem, and if not, why not.

**Comment by kandarp1691** [comment]
This is my code:

 ```
def heathcheck(username, password, server_address, service_name):
    try:
        shell = spur.SshShell(hostname=server_address,
                              username=username,
                              password=password, missing_host_key=spur.ssh.MissingHostKey.accept)
        with shell:
            result = shell.run(['service', service_name, 'status'], allow_error=True)
            if result.output.__contains__('stopped'):
                print result.output
                result_new = shell.run(['service', service_name, 'start'])
                return result_new.output + 'on' + server_address
            else:
                return result.output + 'on' + server_address

    except spur.RunProcessError as e:
        failure_list.append(e.stderr_output)
        print e.stderr_output
    except IOError as e:
        print e.message
    except Exception as e:
        failure_list.append(e.message + ' ' + server_address)
        print e.message
```

**Comment by mwilliamson** [comment]
Presumably that's the new code though, given that `allow_error=True` is in there? I would guess the problem you had before was that the output is in `.output` rather than `stderror_output` when you were catching the `RunProcessError`, which is why you weren't seeing any output, but I could be mistaken.

By "swallowing an exception", I mean behaviour where an exception is caught, but not handled, for instance:

```python
try:
    something_that_might_raise_an_exception()
except Exception as error:
    pass
```

I've no idea what your code is meant to do, so can't comment on whether just printing the message is appropriate, but I generally prefer to either allow the exception (wrapped, if appropriate), or return an object that contains the error, so the caller can decide how best to handle the problem.

On an unrelated note: you shouldn't normally need to call magic methods such as `__contains__` directly. In this case, `"stopped" in result.output` would be idiomatic. Similarly, I think the convention is to call `str(error)` rather than `error.message` for exceptions (I think `message` is deprecated in Python 2 and removed in Python 3).
